<% project_name = 'workout-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= workout-api %>_development

test:
  <<: *default
  database: <%= workout-api %>_test
